### ISSUE TITLE
App crash in emulator

### ISSUE THREAD

**Issue by RaimundWege** [hemanthrajv/flutter_compass#1]
**Error Log**
```
09-18 15:34:55.247 8917-8917/ubilabs.net.trufiBeta E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ubilabs.net.trufiBeta, PID: 8917
    java.lang.RuntimeException: Unable to start activity ComponentInfo{ubilabs.net.trufiBeta/ubilabs.net.trufiBeta.MainActivity}: java.lang.IllegalStateException: sensorManager.getDefaultSensor(sensorType) must not be null
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.IllegalStateException: sensorManager.getDefaultSensor(sensorType) must not be null
        at com.hemanthraj.fluttercompass.FlutterCompassPlugin.<init>(FlutterCompassPlugin.kt:31)
        at com.hemanthraj.fluttercompass.FlutterCompassPlugin.<init>(FlutterCompassPlugin.kt:11)
        at com.hemanthraj.fluttercompass.FlutterCompassPlugin$Companion.registerWith(FlutterCompassPlugin.kt:25)
        at com.hemanthraj.fluttercompass.FlutterCompassPlugin.registerWith(FlutterCompassPlugin.kt)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:19)
        at ubilabs.net.trufiBeta.MainActivity.onCreate(MainActivity.kt:11)
        at android.app.Activity.performCreate(Activity.java:5990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
        at android.app.ActivityThread.access$800(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5254) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
```

**Comment by hemanthrajv** [comment]
Hope `Sensor.TYPE_ROTATION_VECTOR` is not available on emulators. Please try running on real device.

**Comment by RaimundWege** [comment]
On real devices everything works fine but what happens on devices with no compass? It should be possible to prevent this app crash.

**Comment by zhen1991** [comment]
Hi!
Is there any update on this object??
thnx:)

**Comment by RaimundWege** [comment]
@zhen1991 version 0.0.2 is available and on devices with no compass you can run the app but you won't receive updates.

**Comment by zukinaru** [comment]
Hi i got this error on real device, any solution ?
